### ISSUE TITLE
fatal error: nvscibuf.h: No such file or directory

### ISSUE THREAD

**Issue by WangFengtu1996** [NVIDIA-AI-IOT/cuDLA-samples#12]
* Env
```
(base) orin@orin-root:~/workspace/cuDLA-samples$ sudo jetson_release
[sudo] password for orin:
Software part of jetson-stats 4.2.4 - (c) 2024, Raffaello Bonghi
Model: Jetson AGX Orin Developer Kit - Jetpack 5.1.2 [L4T 35.4.1]
NV Power Mode[0]: MAXN
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - P-Number: p3701-0005
 - Module: NVIDIA Jetson AGX Orin (64GB ram)
Platform:
 - Distribution: Ubuntu 20.04 focal
 - Release: 5.10.120-tegra
jtop:
 - Version: 4.2.4
 - Service: Active
Libraries:
 - CUDA: 11.4.315
 - cuDNN: 8.6.0.166
 - TensorRT: 5.1.2
 - VPI: 2.3.9
 - Vulkan: 1.3.204
 - OpenCV: 4.6.0 - with CUDA: YES
```
* build command
I try both in hybrid mode and standalone mode. I got same error. `src/cudla_context_standalone.h:30:10: fatal error: nvscibuf.h: No such file or directory`
```
make run 
make run USE_DLA_STANDALONE_MODE=1
```

* I search solution  in Internel. But I can not fix the bug . https://forums.developer.nvidia.com/t/where-is-nvscibuf-h/107802
